### PR TITLE
Update README.org

### PR DESCRIPTION
**Pull request by q60**
+ Update screenshot

+ Make table looking better

+ Change my name

:point_right: :point_left:

### CODE REVIEW

**Comment by q60** [comment]
apropos, what do you think about replacing shell script with a Makefile? that would be more consistent. three rules would be enough for that: build, install, uninstall

**Comment by RustemB** [comment]
good, i'll do this
also, you can help me

**Comment by q60** [comment]
> good, i'll do this
> also, you can help me

sure, i can make it

**Comment by q60** [comment]
but AUR package should be updated after that according to new build system

**Pull request merged**
